repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
      - id: dockerfile_lint
