name: Build DrumBurp-Builder Docker images

on: [push]

jobs:
  build:
    name: Windows
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker build
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: whatang/drumburp-builder
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.windows
          cache: true
