name: Build DrumBurp-Builder Docker images

on: [push]

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Check where we are
        run: ls "C:\Program Files (x86)"
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker build
        run: docker build -f Dockerfile.windows .
